###  Cancel Transaction
@transaction_id = 787827874270973749283748


put {{customer-url}}/api/transaction/{{transaction_id}}/event
Authorization: Bearer {{token}}
Accept: application/json

{
  "trigger": "transaction_cancelled"
}