@packageId=
@docuementId=
@approvalId=
@fieldId=

### Creates a new approval
post {{hostname}}/api/packages/{{packageId}}/documents/{{docuementId}}/approvals
Accept: application/json
Authorization: Basic {{api}}

{
  "fields": [
    {
      "value": "string",
      "name": "string",
      "type": "SIGNATURE",
      "validation": {
        "maxLength": 0,
        "pattern": "string",
        "required": true,
        "errorMessage": "string",
        "errorCode": 0,
        "enum": [
          "string"
        ],
        "minLength": 0,
        "group": "string",
        "minimumRequired": 0
      },
      "binding": "string",
      "id": "string",
      "data": {
        "additionalProp1": {},
        "additionalProp2": {},
        "additionalProp3": {}
      },
      "page": 0,
      "left": 0,
      "extractAnchor": {
        "topOffset": 100,
        "characterIndex": 3,
        "anchorPoint": "TOPLEFT",
        "index": 2,
        "text": "Signature:",
        "width": 200,
        "height": 50,
        "leftOffset": 20
      },
      "extract": true,
      "subtype": "FULLNAME",
      "width": 0,
      "top": 0,
      "height": 0,
      "textAlignment": "string"
    }
  ],
  "name": "string",
  "id": "string",
  "data": {
    "additionalProp1": {},
    "additionalProp2": {},
    "additionalProp3": {}
  },
  "role": "string",
  "optional": true,
  "enforceCaptureSignature": true,
  "accepted": "2024-12-09T15:07:34.125Z",
  "signed": "2024-12-09T15:07:34.125Z"
}

### Updates an existing approval
put {{hostname}}/api/packages/{{packageId}}/documents/{{documentId}}/approvals/{{approvalId}}
Accept: application/json
Authorization: Basic {{api}}

[
  {
    "fields": [
      {
        "value": "string",
        "name": "string",
        "type": "SIGNATURE",
        "validation": {
          "maxLength": 0,
          "pattern": "string",
          "required": true,
          "errorMessage": "string",
          "errorCode": 0,
          "enum": [
            "string"
          ],
          "minLength": 0,
          "group": "string",
          "minimumRequired": 0
        },
        "binding": "string",
        "id": "string",
        "data": {
          "additionalProp1": {},
          "additionalProp2": {},
          "additionalProp3": {}
        },
        "page": 0,
        "left": 0,
        "extractAnchor": {
          "topOffset": 100,
          "characterIndex": 3,
          "anchorPoint": "TOPLEFT",
          "index": 2,
          "text": "Signature:",
          "width": 200,
          "height": 50,
          "leftOffset": 20
        },
        "extract": true,
        "subtype": "FULLNAME",
        "width": 0,
        "top": 0,
        "height": 0,
        "textAlignment": "string"
      }
    ],
    "name": "string",
    "id": "string",
    "data": {
      "additionalProp1": {},
      "additionalProp2": {},
      "additionalProp3": {}
    },
    "role": "string",
    "optional": true,
    "enforceCaptureSignature": true,
    "accepted": "2024-12-09T15:09:21.157Z",
    "signed": "2024-12-09T15:09:21.157Z"
  }
]

### Retrieves an existing approval
get {{hostname}}/api/packages/{{packageId}}/documents/{{documentId}}/approvals/{{approvalId}}
Accept: application/json
Authorization: Basic {{api}}

### Deletes an existing approval.
delete {{hostname}}/api/packages/{{packageId}}/documents/{{documentId}}/approvals/{{approvalId}}
Accept: application/json
Authorization: Basic {{api}}

### Creates a new field with an autogenerated name related to an existing approval
post {{hostname}}/api/packages/{{packageId}}/documents/{{documentId}}/approvals/{{approvalId}}/fields
Accept: application/json
Authorization: Basic {{api}}

{
  "value": "string",
  "name": "string",
  "type": "SIGNATURE",
  "validation": {
    "maxLength": 0,
    "pattern": "string",
    "required": true,
    "errorMessage": "string",
    "errorCode": 0,
    "enum": [
      "string"
    ],
    "minLength": 0,
    "group": "string",
    "minimumRequired": 0
  },
  "binding": "string",
  "id": "string",
  "data": {
    "additionalProp1": {},
    "additionalProp2": {},
    "additionalProp3": {}
  },
  "page": 0,
  "left": 0,
  "extractAnchor": {
    "topOffset": 100,
    "characterIndex": 3,
    "anchorPoint": "TOPLEFT",
    "index": 2,
    "text": "Signature:",
    "width": 200,
    "height": 50,
    "leftOffset": 20
  },
  "extract": true,
  "subtype": "FULLNAME",
  "width": 0,
  "top": 0,
  "height": 0,
  "textAlignment": "string"
}

### Retrieves an existing field related to an existing approval
get {{hostname}}/api/packages/{{packageId}}/documents/{{documentId}}/approvals/{{approvalId}}/fields/{{fieldId}}
Accept: application/json
Authorization: Basic {{api}}

### Updates an existing field related to an existing approval
put {{hostname}}/api/packages/{{packageId}}/documents/{{documentId}}/approvals/{{approvalId}}/fields/{{fieldId}}
Accept: application/json
Authorization: Basic {{api}}

{
  "value": "string",
  "name": "string",
  "type": "SIGNATURE",
  "validation": {
    "maxLength": 0,
    "pattern": "string",
    "required": true,
    "errorMessage": "string",
    "errorCode": 0,
    "enum": [
      "string"
    ],
    "minLength": 0,
    "group": "string",
    "minimumRequired": 0
  },
  "binding": "string",
  "id": "string",
  "data": {
    "additionalProp1": {},
    "additionalProp2": {},
    "additionalProp3": {}
  },
  "page": 0,
  "left": 0,
  "extractAnchor": {
    "topOffset": 100,
    "characterIndex": 3,
    "anchorPoint": "TOPLEFT",
    "index": 2,
    "text": "Signature:",
    "width": 200,
    "height": 50,
    "leftOffset": 20
  },
  "extract": true,
  "subtype": "FULLNAME",
  "width": 0,
  "top": 0,
  "height": 0,
  "textAlignment": "string"
}

### Creates a new field related to an existing approval
post {{hostname}}/api/packages/{{packageId}}/documents/{{documentId}}/approvals/{{approvalId}}/fields/{{fieldId}}
Accept: application/json
Authorization: Basic {{api}}

{
  "value": "string",
  "name": "string",
  "type": "SIGNATURE",
  "validation": {
    "maxLength": 0,
    "pattern": "string",
    "required": true,
    "errorMessage": "string",
    "errorCode": 0,
    "enum": [
      "string"
    ],
    "minLength": 0,
    "group": "string",
    "minimumRequired": 0
  },
  "binding": "string",
  "id": "string",
  "data": {
    "additionalProp1": {},
    "additionalProp2": {},
    "additionalProp3": {}
  },
  "page": 0,
  "left": 0,
  "extractAnchor": {
    "topOffset": 100,
    "characterIndex": 3,
    "anchorPoint": "TOPLEFT",
    "index": 2,
    "text": "Signature:",
    "width": 200,
    "height": 50,
    "leftOffset": 20
  },
  "extract": true,
  "subtype": "FULLNAME",
  "width": 0,
  "top": 0,
  "height": 0,
  "textAlignment": "string"
}

### Deletes an existing field related to an existing approval
delete {{hostname}}/api/packages/{{packageId}}/documents/{{documentId}}/approvals/{{approvalId}}/fields/{{fieldId}}
Accept: application/json
Authorization: Basic {{api}}

### Retrieves all signable approvals
get {{hostname}}/api/packages/{{packageId}}/documents/{{documentId}}/approvals/{{approvalId}}/fields/{{fieldId}}
Accept: application/json
Authorization: Basic {{api}}

### Updates the conditions for a given field
put {{hostname}}/api/packages/{{packageId}}/documents/{{documentId}}/approvals/{{approvalId}}/fields/{{fieldId}}/conditionalFields
Accept: application/json
Authorization: Basic {{api}}

{
  "value": "string",
  "name": "string",
  "type": "SIGNATURE",
  "validation": {
    "maxLength": 0,
    "pattern": "string",
    "required": true,
    "errorMessage": "string",
    "errorCode": 0,
    "enum": [
      "string"
    ],
    "minLength": 0,
    "group": "string",
    "minimumRequired": 0
  },
  "binding": "string",
  "id": "string",
  "data": {
    "additionalProp1": {},
    "additionalProp2": {},
    "additionalProp3": {}
  },
  "page": 0,
  "left": 0,
  "extractAnchor": {
    "topOffset": 100,
    "characterIndex": 3,
    "anchorPoint": "TOPLEFT",
    "index": 2,
    "text": "Signature:",
    "width": 200,
    "height": 50,
    "leftOffset": 20
  },
  "extract": true,
  "subtype": "FULLNAME",
  "width": 0,
  "top": 0,
  "height": 0,
  "textAlignment": "string",
  "conditions": [
    {
      "action": "document['49a221e06c609157e214d78605a9c8fbf84937a5087ee737'].field['fuwgAytPFeoM'].disabled = false",
      "condition": "document['49a221e06c609157e214d78605a9c8fbf84937a5087ee737'].field['XOdevBtCxusH'].value == 'X'",
      "id": "55fc2124-b52e-4166-b603-5412b35bd5ff"
    }
  ]
}