### Retrieves the settings for a password policy
get {{hostname}}/api/passwordPolicy
Accept: application/json
Authorization: Basic {{api}}

### Updates the settings for a password policy
put {{hostname}}/api/passwordPolicy
Accept: application/json
Authorization: Basic {{api}}

{
  "age": 0,
  "history": 0,
  "length": 8,
  "requiredRules": 2,
  "expiry": 0,
  "includeUppercase": true,
  "includeLowercase": true,
  "includeNumbers": true,
  "includeSpecialCharacters": true,
  "enableExpiryNotifications": false,
  "firstReminder": 14,
  "repeatReminderCount": 5,
  "maxInvalidLoginAttempts": 10
}